modLoader = "javafml"
loaderVersion = "[${forge},)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "deepslateinstamine"
version = "${version}"
displayName = "Deepslateinstamine"
authors = "nicguzzo"
description = '''
Deepslate Instamine!
'''
#logoFile = ""

[[dependencies.deepslateinstamine]]
modId = "forge"
mandatory = true
versionRange = "[${forge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.deepslateinstamine]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.deepslateinstamine]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"
